2019-08-13 13:20:34,106 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:20:35,994 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:20:52,104 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:20:53,331 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:21:14,206 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:21:16,286 ERROR: Exception on /index [GET] [in d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myprojects\flask_tutorial_projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\MyProjects\flask_tutorial_projects\microblog\app\routes.py", line 24, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-08-13 13:23:22,790 INFO: Microblog startup [in D:\MyProjects\flask_tutorial_projects\microblog\app\__init__.py:46]
2019-08-13 13:23:49,794 INFO: Microblog startup [in D:\MyProjects\flask_tutorial_projects\microblog\app\__init__.py:46]
